name: rewe_app_clone
description: A Flutter clone of the REWE shopping app for iOS
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  hooks_riverpod: ^2.4.9
  flutter_hooks: ^0.20.3

  # Data Models & Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Networking
  dio: ^5.3.2

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0

  # UI Components
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.0

  # Utilities
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fixtures/