import '../../models/product.dart';
import '../../models/user.dart';

class MockData {
  static List<Product> get products => [
    Product(
      id: '1',
      name: 'Bio Äpfel Braeburn',
      description: 'Frische Bio-Äpfel aus kontrolliert biologischem Anbau. Süß und knackig.',
      price: 2.99,
      originalPrice: 3.49,
      imageUrls: ['https://via.placeholder.com/300x300/FF0000/FFFFFF?text=Apfel'],
      category: 'fruits-vegetables',
      brand: 'Bio Zentrale',
      isAvailable: true,
      rating: 4.5,
      reviewCount: 127,
      unit: 'kg',
      unitSize: 1.0,
      tags: ['bio', 'regional', 'saisonal'],
      nutritionGrade: 'A',
      nutritionFacts: {
        'Kalorien': '52 kcal',
        'Zucker': '10,4g',
        'Ballaststoffe': '2,4g',
        'Vitamin C': '4,6mg',
      },
      variants: [
        const ProductVariant(
          id: 'apple-1kg',
          name: '1kg',
          price: 2.99,
          isAvailable: true,
          type: 'weight',
        ),
        const ProductVariant(
          id: 'apple-2kg',
          name: '2kg',
          price: 5.49,
          isAvailable: true,
          type: 'weight',
        ),
      ],
      hasOffer: true,
      offerText: '15% günstiger',
      offerValidUntil: DateTime.now().add(const Duration(days: 3)),
      isOrganic: true,
      isVegan: true,
      isVegetarian: true,
      isGlutenFree: true,
      isLactoseFree: true,
    ),

    const Product(
      id: '2',
      name: 'Vollmilch 3,5% Bio',
      description: 'Frische Bio-Vollmilch von Weidekühen aus regionaler Landwirtschaft.',
      price: 1.29,
      originalPrice: 1.29,
      imageUrls: ['https://via.placeholder.com/300x300/FFFFFF/0000FF?text=Milch'],
      category: 'dairy',
      brand: 'Andechser Natur',
      isAvailable: true,
      rating: 4.8,
      reviewCount: 89,
      unit: 'l',
      unitSize: 1.0,
      tags: ['bio', 'regional', 'frisch'],
      nutritionGrade: 'B',
      nutritionFacts: {
        'Kalorien': '64 kcal',
        'Fett': '3,5g',
        'Eiweiß': '3,4g',
        'Kohlenhydrate': '4,8g',
      },
      variants: [
        ProductVariant(
          id: 'milk-1l',
          name: '1 Liter',
          price: 1.29,
          isAvailable: true,
          type: 'volume',
        ),
      ],
      hasOffer: false,
      isOrganic: true,
      isVegan: false,
      isVegetarian: true,
      isGlutenFree: true,
      isLactoseFree: false,
    ),

    Product(
      id: '3',
      name: 'Hähnchenbrust Filet',
      description: 'Frisches Hähnchenbrust-Filet aus artgerechter Haltung.',
      price: 8.99,
      originalPrice: 9.99,
      imageUrls: ['https://via.placeholder.com/300x300/FFC0CB/000000?text=Huhn'],
      category: 'meat-fish',
      brand: 'Wiesenhof',
      isAvailable: true,
      rating: 4.2,
      reviewCount: 156,
      unit: 'kg',
      unitSize: 0.6,
      tags: ['frisch', 'regional', 'premium'],
      nutritionGrade: 'A',
      nutritionFacts: {
        'Kalorien': '165 kcal',
        'Eiweiß': '31g',
        'Fett': '3,6g',
        'Kohlenhydrate': '0g',
      },
      variants: [
        const ProductVariant(
          id: 'chicken-600g',
          name: '600g',
          price: 8.99,
          isAvailable: true,
          type: 'weight',
        ),
        const ProductVariant(
          id: 'chicken-1kg',
          name: '1kg',
          price: 14.99,
          isAvailable: true,
          type: 'weight',
        ),
      ],
      hasOffer: true,
      offerText: '1€ sparen',
      offerValidUntil: DateTime.now().add(const Duration(days: 2)),
      isOrganic: false,
      isVegan: false,
      isVegetarian: false,
      isGlutenFree: true,
      isLactoseFree: true,
    ),

    const Product(
      id: '4',
      name: 'Bananen',
      description: 'Süße, reife Bananen aus fairem Handel.',
      price: 1.99,
      originalPrice: 1.99,
      imageUrls: ['https://via.placeholder.com/300x300/FFFF00/000000?text=Banane'],
      category: 'fruits-vegetables',
      brand: 'Fairtrade',
      isAvailable: true,
      rating: 4.6,
      reviewCount: 203,
      unit: 'kg',
      unitSize: 1.0,
      tags: ['fairtrade', 'süß', 'tropisch'],
      nutritionGrade: 'A',
      nutritionFacts: {
        'Kalorien': '89 kcal',
        'Zucker': '12,2g',
        'Kalium': '358mg',
        'Vitamin B6': '0,4mg',
      },
      variants: [
        ProductVariant(
          id: 'banana-1kg',
          name: '1kg',
          price: 1.99,
          isAvailable: true,
          type: 'weight',
        ),
      ],
      hasOffer: false,
      isOrganic: false,
      isVegan: true,
      isVegetarian: true,
      isGlutenFree: true,
      isLactoseFree: true,
    ),

    const Product(
      id: '5',
      name: 'Vollkornbrot',
      description: 'Herzhaftes Vollkornbrot aus der Bäckerei, reich an Ballaststoffen.',
      price: 2.49,
      originalPrice: 2.49,
      imageUrls: ['https://via.placeholder.com/300x300/8B4513/FFFFFF?text=Brot'],
      category: 'bakery',
      brand: 'Bäckerei Schmidt',
      isAvailable: true,
      rating: 4.4,
      reviewCount: 78,
      unit: 'g',
      unitSize: 500.0,
      tags: ['vollkorn', 'frisch', 'ballaststoffreich'],
      nutritionGrade: 'B',
      nutritionFacts: {
        'Kalorien': '247 kcal',
        'Ballaststoffe': '7,4g',
        'Eiweiß': '8,4g',
        'Kohlenhydrate': '45,2g',
      },
      variants: [
        ProductVariant(
          id: 'bread-500g',
          name: '500g',
          price: 2.49,
          isAvailable: true,
          type: 'weight',
        ),
        ProductVariant(
          id: 'bread-1kg',
          name: '1kg',
          price: 4.49,
          isAvailable: true,
          type: 'weight',
        ),
      ],
      hasOffer: false,
      isOrganic: false,
      isVegan: true,
      isVegetarian: true,
      isGlutenFree: false,
      isLactoseFree: true,
    ),

    Product(
      id: '6',
      name: 'Orangensaft 100%',
      description: 'Frisch gepresster Orangensaft ohne Zuckerzusatz.',
      price: 2.79,
      originalPrice: 3.29,
      imageUrls: ['https://via.placeholder.com/300x300/FFA500/FFFFFF?text=O-Saft'],
      category: 'beverages',
      brand: 'Innocent',
      isAvailable: true,
      rating: 4.7,
      reviewCount: 145,
      unit: 'l',
      unitSize: 1.0,
      tags: ['100% frucht', 'ohne zusätze', 'vitaminreich'],
      nutritionGrade: 'B',
      nutritionFacts: {
        'Kalorien': '45 kcal',
        'Vitamin C': '50mg',
        'Zucker': '8,8g',
        'Folsäure': '30μg',
      },
      variants: [
        const ProductVariant(
          id: 'juice-1l',
          name: '1 Liter',
          price: 2.79,
          isAvailable: true,
          type: 'volume',
        ),
        const ProductVariant(
          id: 'juice-500ml',
          name: '500ml',
          price: 1.59,
          isAvailable: true,
          type: 'volume',
        ),
      ],
      hasOffer: true,
      offerText: '15% Rabatt',
      offerValidUntil: DateTime.now().add(const Duration(days: 5)),
      isOrganic: false,
      isVegan: true,
      isVegetarian: true,
      isGlutenFree: true,
      isLactoseFree: true,
    ),
  ];

  static List<Category> get categories => [
    const Category(
      id: 'fruits-vegetables',
      name: 'Obst & Gemüse',
      imageUrl: 'https://via.placeholder.com/200x120/00FF00/FFFFFF?text=Obst',
      iconUrl: 'https://via.placeholder.com/64x64/00FF00/FFFFFF?text=🍎',
      productCount: 245,
      isPopular: true,
    ),
    const Category(
      id: 'meat-fish',
      name: 'Fleisch & Fisch',
      imageUrl: 'https://via.placeholder.com/200x120/FF6B6B/FFFFFF?text=Fleisch',
      iconUrl: 'https://via.placeholder.com/64x64/FF6B6B/FFFFFF?text=🥩',
      productCount: 187,
      isPopular: true,
    ),
    const Category(
      id: 'dairy',
      name: 'Milchprodukte',
      imageUrl: 'https://via.placeholder.com/200x120/FFFFFF/000000?text=Milch',
      iconUrl: 'https://via.placeholder.com/64x64/FFFFFF/000000?text=🥛',
      productCount: 156,
      isPopular: false,
    ),
    const Category(
      id: 'bakery',
      name: 'Bäckerei',
      imageUrl: 'https://via.placeholder.com/200x120/D2691E/FFFFFF?text=Brot',
      iconUrl: 'https://via.placeholder.com/64x64/D2691E/FFFFFF?text=🍞',
      productCount: 98,
      isPopular: true,
    ),
    const Category(
      id: 'beverages',
      name: 'Getränke',
      imageUrl: 'https://via.placeholder.com/200x120/87CEEB/000000?text=Drinks',
      iconUrl: 'https://via.placeholder.com/64x64/87CEEB/000000?text=🥤',
      productCount: 234,
      isPopular: false,
    ),
    const Category(
      id: 'frozen',
      name: 'Tiefkühlkost',
      imageUrl: 'https://via.placeholder.com/200x120/E0E0E0/000000?text=TK',
      iconUrl: 'https://via.placeholder.com/64x64/E0E0E0/000000?text=🧊',
      productCount: 123,
      isPopular: false,
    ),
  ];

  static User get mockUser => User(
    id: 'user_123',
    email: 'max.mustermann@example.com',
    firstName: 'Max',
    lastName: 'Mustermann',
    phoneNumber: '+49 123 456789',
    dateOfBirth: '1990-01-15',
    profileImageUrl: 'https://via.placeholder.com/150x150/0066CC/FFFFFF?text=MM',
    createdAt: DateTime(2023, 1, 1),
    updatedAt: DateTime(2024, 1, 1),
    emailVerified: true,
    phoneVerified: false,
    preferences: const UserPreferences(
      pushNotifications: true,
      emailNotifications: true,
      smsNotifications: false,
      promotionalNotifications: true,
      language: 'de',
      darkMode: false,
      dietaryRestrictions: ['vegetarian'],
      allergens: ['nuts'],
      preferredStore: 'rewe_berlin_1',
    ),
    loyalty: const UserLoyalty(
      points: 1250,
      tier: 'Gold',
      totalSpent: 2450.75,
      ordersCount: 47,
      nextTierThreshold: 5000.0,
      badges: ['eco_warrior', 'frequent_buyer', 'review_master'],
    ),
  );

  static List<Order> get mockOrders => [
    Order(
      id: 'ORD_001',
      status: 'delivered',
      orderDate: DateTime.now().subtract(const Duration(days: 3)),
      deliveryDate: DateTime.now().subtract(const Duration(days: 2)),
      total: 45.67,
      subtotal: 41.68,
      deliveryFee: 3.99,
      discount: 0.0,
      items: [
        const CartItem(
          productId: '1',
          variantId: 'apple-1kg',
          quantity: 2,
          price: 2.99,
          name: 'Bio Äpfel Braeburn',
          imageUrl: 'https://via.placeholder.com/100x100/FF0000/FFFFFF?text=Apfel',
        ),
        const CartItem(
          productId: '2',
          variantId: 'milk-1l',
          quantity: 3,
          price: 1.29,
          name: 'Vollmilch 3,5% Bio',
          imageUrl: 'https://via.placeholder.com/100x100/FFFFFF/0000FF?text=Milch',
        ),
      ],
      address: const DeliveryAddress(
        id: 'addr_1',
        label: 'Zuhause',
        street: 'Musterstraße',
        houseNumber: '123',
        postalCode: '10115',
        city: 'Berlin',
        additionalInfo: '2. Stock, rechts',
        isDefault: true,
        latitude: 52.5200,
        longitude: 13.4050,
      ),
      paymentMethod: const PaymentMethod(
        id: 'pay_1',
        type: 'credit_card',
        displayName: 'Visa Kreditkarte',
        maskedNumber: '**** 1234',
        isDefault: true,
        expiryMonth: '12',
        expiryYear: '25',
      ),
      trackingNumber: 'DHL123456789',
      deliverySlot: 'Heute 14:00 - 16:00',
    ),
    Order(
      id: 'ORD_002',
      status: 'on_the_way',
      orderDate: DateTime.now().subtract(const Duration(hours: 4)),
      deliveryDate: DateTime.now().add(const Duration(hours: 2)),
      total: 28.45,
      subtotal: 24.46,
      deliveryFee: 3.99,
      discount: 0.0,
      items: [
        const CartItem(
          productId: '3',
          variantId: 'chicken-600g',
          quantity: 1,
          price: 8.99,
          name: 'Hähnchenbrust Filet',
          imageUrl: 'https://via.placeholder.com/100x100/FFC0CB/000000?text=Huhn',
        ),
        const CartItem(
          productId: '6',
          variantId: 'juice-1l',
          quantity: 2,
          price: 2.79,
          name: 'Orangensaft 100%',
          imageUrl: 'https://via.placeholder.com/100x100/FFA500/FFFFFF?text=O-Saft',
        ),
      ],
      address: const DeliveryAddress(
        id: 'addr_1',
        label: 'Zuhause',
        street: 'Musterstraße',
        houseNumber: '123',
        postalCode: '10115',
        city: 'Berlin',
        isDefault: true,
        latitude: 52.5200,
        longitude: 13.4050,
      ),
      paymentMethod: const PaymentMethod(
        id: 'pay_2',
        type: 'paypal',
        displayName: 'PayPal',
        maskedNumber: 'max@example.com',
        isDefault: false,
      ),
      trackingNumber: 'DHL987654321',
      deliverySlot: 'Heute 18:00 - 20:00',
    ),
  ];

  static List<DeliveryAddress> get mockAddresses => [
    const DeliveryAddress(
      id: 'addr_1',
      label: 'Zuhause',
      street: 'Musterstraße',
      houseNumber: '123',
      postalCode: '10115',
      city: 'Berlin',
      additionalInfo: '2. Stock, rechts',
      isDefault: true,
      latitude: 52.5200,
      longitude: 13.4050,
    ),
    const DeliveryAddress(
      id: 'addr_2',
      label: 'Büro',
      street: 'Alexanderplatz',
      houseNumber: '1',
      postalCode: '10178',
      city: 'Berlin',
      additionalInfo: 'Eingang B, 5. Etage',
      isDefault: false,
      latitude: 52.5219,
      longitude: 13.4132,
    ),
  ];
}